version: "3.3"
services:
  # nom du conteneur eureka
  discovery:
    build: D:\5SAE5\AgriShare-project\back\AgriShare\Backend\EurekaServer
    ports:
      - "8761:8761"
    image: "eureka"


  # nom du conteneur eureka
  geteway:
    build: D:\5SAE5\AgriShare-project\back\AgriShare\Backend\GateWay
    container_name: geteway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8096:8096"
    image: "gateway"


  # nom du conteneur projet(MongoDB)
  projet:
    build: D:\5SAE5\AgriShare-project\back\AgriShare\Backend\MS-Projet
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.data.mongodb.uri=mongodb://mongodb:27017/AgriShare
    ports:
      - "8093:8093"
    image: "projet-service"
    depends_on:
      - discovery
      - mongodb
      - config-server


  # nom du conteneur Recolte(MongoDB)
  recolte:
    build: D:\5SAE5\AgriShare-project\back\AgriShare\Backend\MS-Recolte
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.data.mongodb.uri=mongodb://mongodb:27017/AgriShare
    ports:
      - "8094:8094"
    image: "recolte-service"
    depends_on:
      - discovery
      - mongodb


  # nom du conteneur Ressources(MongoDB)
  ressources:
    build: D:\5SAE5\AgriShare-project\back\AgriShare\Backend\MS-Ressources
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.data.mongodb.uri=mongodb://mongodb:27017/AgriShare
    ports:
      - "8095:8095"
    image: "ressources-service"
    depends_on:
      - discovery
      - mongodb

  # nom du conteneur Formation(Mysql)

  formation:
    build: D:\5SAE5\AgriShare-project\back\AgriShare\Backend\MS-Formation
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/AgriShare?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
    ports:
      - "8090:8090"
    image: "formation-service"
    depends_on:
      - discovery
      - docker-mysql


  # nom du conteneur Reclamation(Mysql)

  reclamation:
    build: D:\5SAE5\AgriShare-project\back\AgriShare\Backend\MS-Reclamation
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/AgriShare?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
    ports:
      - "8092:8092"
    image: "reclamation-service"
    depends_on:
      - discovery
      - docker-mysql


  # nom du conteneur Partenariat(Mysql)

  partenariat:
    build: D:\5SAE5\AgriShare-project\back\AgriShare\Backend\MS-Partenariat
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/AgriShare?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
    ports:
      - "8091:8091"
    image: "partenariat-service"
    depends_on:
      - discovery
      - docker-mysql


  ms-user:
    build: D:\5SAE5\AgriShare-project\back\AgriShare\Backend\MS-User
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
      - MONGO_URI=mongodb://mongodb:27017/AgriShare
    ports:
      - "3001:3000"
    image: "user-service"
    depends_on:
      - discovery
      - mongodb


  config-server:
    build: D:\5SAE5\AgriShare-project\back\AgriShare\Backend\Config-Server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.application.name=Config-Server
      - spring.profiles.active=native
      - spring.cloud.config.server.native.searchLocations=./src/main/resources
    ports:
      - "8888:8888"
    image: "config-server"
    depends_on:
      - discovery

#  front-service:
#    build: D:\5SAE5\AgriShare-project\front\Frontoffice\AgriShare-front
#    ports:
#      - 4200:4200
#    depends_on:
#      - geteway


    # Keycloak avec MySQL
#  keycloak:
#    image: quay.io/keycloak/keycloak:23.0.0
#    environment:
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#      - KC_DB=mysql
#      - KC_DB_USERNAME=keycloak
#      - KC_DB_PASSWORD=password   # Correspond à MYSQL_PASSWORD de docker-mysql
#      - KC_DB_URL_PORT=3306       # Port par défaut de MySQL
#      - KC_DB_URL_HOST=keycloak-db
#    ports:
#      - "8082:8080"
#    depends_on:
#      - keycloak-db
#    command:
#      - "start-dev"
#      - "-Dkeycloak.migration.action=import"
#      - "-Dkeycloak.migration.provider=dir"
#      - "-Dkeycloak.migration.dir=/opt/keycloak/migration"
#    volumes:
#      - ./keycloak_data:/opt/keycloak/migration
#    networks:
#      - keycloak-net

  # nom du conteneur Mysql
  docker-mysql:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=AgriShare
    ports:
      - 3308:3306


#  keycloak-db:
#    image: "mysql:8.0.38"
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=keycloak
#      - MYSQL_USER=keycloak               # Utilisateur MySQL pour Keycloak
#      - MYSQL_PASSWORD=password          # Mot de passe de l'utilisateur keycloak
#    ports:
#      - 3309:3306
#    networks:
#      - keycloak-net
  # nom du conteneur MongoDB
  mongodb:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_DATABASE=AgriShare
    ports:
      - 27017:27017

volumes:
  db-data:


