
version: "3.3"

services:
  # Eureka Server
  discovery:
    build: C:\Users\LENOVO\Desktop\agrishareMicro\AgriShare-Back\Backend\EurekaServer
    ports:
      - "8761:8761"
    image: "eureuka"
    networks:
      - app-network

  # MS-Partenariat
  mspartenariat:
    build: C:\Users\LENOVO\Desktop\agrishareMicro\AgriShare-Back\Backend\MS-Partenariat
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql_1:3306/AgriShare?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    ports:
      - "8091:8091"
    image: "partenariat"
    depends_on:
      - discovery
      - docker-mysql_1
      - gateway
    networks:
      - app-network

  # MS-Gateway
  gateway:
    build: C:\Users\LENOVO\Desktop\agrishareMicro\AgriShare-Back\Backend\GateWay
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8096:8096"
    image: "gateway"
    depends_on:
      - discovery
    networks:
      - app-network

  # MySQL Database
  docker-mysql_1:
    image: "mysql:5.6"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=AgriShare
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
