version: "3.3"
services:
  # nom du conteneur eureka
  discovery:
    build: C:\Agri-back\AgriShare-Back\Backend\EurekaServer
    ports:
      - "8761:8761"
    image: "eureka"
    networks:
      - keycloak-net

  # nom du conteneur gateway
  geteway:
    build: C:\Agri-back\AgriShare-Back\Backend\\GateWay
    container_name: geteway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8096:8096"
    image: "gateway"
    networks:
      - keycloak-net

  # nom du conteneur projet(MongoDB)
  projet:
    build: C:\Agri-back\AgriShare-Back\Backend\MS-Projet
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.data.mongodb.uri=mongodb://mongodb:27017/AgriShare
    ports:
      - "8093:8093"
    image: "projet-service"
    depends_on:
      - discovery
      - mongodb
    networks:
      - keycloak-net

  # nom du conteneur Recolte(MongoDB)
  recolte:
    build: C:\Agri-back\AgriShare-Back\Backend\MS-Recolte
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.data.mongodb.uri=mongodb://mongodb:27017/AgriShare
    ports:
      - "8094:8094"
    image: "recolte-service"
    depends_on:
      - discovery
      - mongodb
    networks:
      - keycloak-net

  # nom du conteneur Ressources(MongoDB)
  ressources:
    build: C:\Agri-back\AgriShare-Back\Backend\MS-Ressources
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.data.mongodb.uri=mongodb://mongodb:27017/AgriShare
    ports:
      - "8095:8095"
    image: "ressources-service"
    depends_on:
      - discovery
      - mongodb
    networks:
      - keycloak-net
  # nom du conteneur Formation(Mysql)


  # nom du conteneur Reclamation(Mysql)

  reclamation:
    build: C:\Agri-back\AgriShare-Back\Backend\MS-Reclamation
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/AgriShare?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
    ports:
      - "8092:8092"
    image: "reclamation-service"
    depends_on:
      - discovery
      - docker-mysql
    networks:
      - keycloak-net

  # nom du conteneur Partenariat(Mysql)

  partenariat:
    build: C:\Agri-back\AgriShare-Back\Backend\MS-Partenariat
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/AgriShare?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
    ports:
      - "8091:8091"
    image: "partenariat-service"
    depends_on:
      - discovery
      - docker-mysql
    networks:
      - keycloak-net

  front-service:
    build: C:\Agri-front\AgriShare-Front
    ports:
      - 4200:4200
    depends_on:
      - geteway

  # nom du conteneur Mysql
  docker-mysql:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=AgriShare
      - MYSQL_USER=keycloak               # Utilisateur MySQL pour Keycloak
      - MYSQL_PASSWORD=password          # Mot de passe de l'utilisateur keycloak
    ports:
      - 3308:3306
    networks:
      - keycloak-net


  # nom du conteneur MongoDB
  mongodb:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_DATABASE=AgriShare
    ports:
      - 27017:27017
    networks:
      - keycloak-net
volumes:
  db-data:

networks:
  keycloak-net:
    driver: bridge
