version: "3.3"
services:
 # nom du conteneur eureka
  discovery:
    build: C:\Agri-back\AgriShare-Back\Backend\EurekaServer
    ports:
      - "8761:8761" 
    image: "eureka"

  gateway :
      build: C:\Agri-back\AgriShare-Back\Backend\GateWay
      environment:
        - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
      ports:
        - "8096:8096"
      image: "gateway"

 # nom du conteneur projet(MongoDB)
  projet:
    build: C:\Agri-back\AgriShare-Back\Backend\MS-Projet
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.data.mongodb.uri=mongodb://mongodb:27017/AgriShare
    ports:
      - "8093:8093"
    image: "projet-service"
    depends_on:
      - discovery
      - mongodb

 #nom du conteneur Recolte(MongoDB)
  recolte:
    build: C:\Agri-back\AgriShare-Back\Backend\MS-Recolte
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.data.mongodb.uri=mongodb://mongodb:27017/AgriShare
    ports:
      - "8094:8094"
    image: "recolte-service"
    depends_on:
      - discovery
      - mongodb

# nom du conteneur Ressources(MongoDB)
  ressources:
    build: C:\Agri-back\AgriShare-Back\Backend\MS-Ressources
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.data.mongodb.uri=mongodb://mongodb:27017/AgriShare
    ports:
      - "8095:8095"
    image: "ressources-service"
    depends_on:
      - discovery
      - mongodb


 # nom du conteneur Formation(Mysql)

  formation:
      build: C:\Agri-back\AgriShare-Back\Backend\MS-Formation
      environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/AgriShare?autoReconnect=true&useSSL=false
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect

      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      ports:
      - "8090:8090"
      image: "formation-service"
      depends_on:
      - discovery
      - docker-mysql



# nom du conteneur Reclamation(Mysql)

  reclamation:
      build: C:\Agri-back\AgriShare-Back\Backend\MS-Reclamation
      environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/AgriShare?autoReconnect=true&useSSL=false
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect

      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      ports:
      - "8092:8092"
      image: "reclamation-service"
      depends_on:
      - discovery
      - docker-mysql

# nom du conteneur Partenariat(Mysql)

  partenariat:
      build: C:\Agri-back\AgriShare-Back\Backend\MS-Partenariat
      environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/AgriShare?autoReconnect=true&useSSL=false
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect

      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      ports:
      - "8091:8091"
      image: "partenariat-service"
      depends_on:
      - discovery
      - docker-mysql

        # Service Keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    environment:
      - DB_VENDOR=mysql
      - DB_ADDR=docker-mysql:3306
      - DB_DATABASE=AgriShare
      - DB_USER=keycloak
      - DB_PASSWORD=password
    ports:
      - "8180:8080"
    depends_on:
      - docker-mysql
    command:
      - "start-dev"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/opt/keycloak/migration"
    volumes:
      - ./keycloak_data:/opt/keycloak/migration
#    networks:
#      - keycloak-net

    # nom du conteneur Mysql
  docker-mysql:
      image: "mysql:5.6"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=AgriShare
        - MYSQL_USER=keycloak
        - MYSQL_PASSWORD=password
      ports:
        - 3308:3306
#      networks:
#        - keycloak-net

  mongodb:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_DATABASE=AgriShare
    ports:
      - 27017:27017
    networks:
      - default

#networks:
#  keycloak-net:
#    driver: bridge
