services:
  # Eureka Server
  discovery:
    build: D:\Desktop\arcitecture-micro-service\micro-service-formation\AgriShare-Back\Backend\EurekaServer
    ports:
      - "8761:8761"
    image: "eureka"
    networks:
      - app-network

  # MS-Formation
  msformation:
    build: D:\Desktop\arcitecture-micro-service\micro-service-formation\AgriShare-Back\Backend\MS-Formation
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql_1:3306/AgriShare?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    ports:
      - "8090:8090"
    image: "msformation"
    depends_on:
      - discovery
      - docker-mysql_1
      - gateway
    networks:
      - app-network

  # MS-Gateway
  gateway:
    build: D:\Desktop\arcitecture-micro-service\micro-service-formation\AgriShare-Back\Backend\GateWay
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8096:8096"
    image: "gateway"
    depends_on:
      - discovery
    networks:
      - app-network

  # MySQL Database
  docker-mysql_1:
    image: "mysql:5.6"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=AgriShare
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  formation-front:
    build: ./../../AgriShare-Front
    ports:
      - 4200:4200
    depends_on:
      - msformation

networks:
  app-network:
    driver: bridge

volumes:
  db:
